# src/Plugin/PhotoPlugin/Resources/config/grids.yaml
sylius_grid:
    grids:
        app_photographer:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\Plugin\PhotoPlugin\Entity\Photographer
            fields:
                id:
                    type: string
                    label: ID
                    sortable: true
                name:
                    type: string
                    label: Nom
                    sortable: true
                email:
                    type: string
                    label: Email
                    sortable: true
            actions:
                main:
                    create:
                        type: create
                        label: "Ajouter un photographe"
                item:
                    update:
                        type: update
                        label: "Modifier"
                    delete:
                        type: delete
                        label: "Supprimer"

        app_event:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\Plugin\PhotoPlugin\Entity\Event
            fields:
                id:
                    type: string
                    label: ID
                    sortable: true
                name:
                    type: string
                    label: Nom
                    sortable: true
                startDate:
                    type: datetime
                    label: Date de d√©but
                    sortable: true
                endDate:
                    type: datetime
                    label: Date de fin
                    sortable: true
                photographers:
                    type: twig
                    label: Photographes
                    path: photographers
                    options:
                        template: "@PhotoPlugin/Grid/Field/photographers.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
